services:
  elysia-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=production
      - PORT=5555
      - API_KEY=${API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - REDIS_URL=redis://redis:6380
    volumes:
      - ./uploads:/app/uploads
      - ./photos:/app/photos
      - ./inbox:/app/inbox
      - ./src:/app/src
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:alpine
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
